FROM golang:alpine AS builder

WORKDIR /app
COPY ./app/go.mod ./app/go.sum ./
RUN go mod download

COPY ./app/cmd/main.go ./
RUN go build -o /server

FROM scratch AS runner

WORKDIR /
COPY --from=builder /server /server
ENTRYPOINT ["/server"]