apiVersion: v1
kind: Pod
metadata:
  labels:
    type: go
  name: go
spec:
  containers:
  - image: "${ACR_NAME}.azurecr.io/${GO_CONTAINER_NAME}:latest"
    name: go
    env:
    - name: REDIS_HOST
      value: "${REDIS_HOST}.redis.cache.windows.net"
    - name: REDIS_PASSWORD
      value: "${REDIS_PASSWORD}"
    - name: REDIS_PORT
      value: "6380"
    - name: NUM_ITEMS
      value: "50000"
    resources:  
      requests:
          memory: "250Mi"
          cpu: "0.5"
      limits:
          memory: "500Mi"
          cpu: "1"
  dnsPolicy: ClusterFirst
  
  restartPolicy: Never
status: {}
